### ISSUE TITLE
JSON Decode issue in groq tool

### ISSUE THREAD

**Issue by TheBlurHacker** [SreejanPersonal/JARVIS-AGI#1]
I am getting this error: 

Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I don't know why, but I think the JSON response has some issues, its is giving 500 error code.

**Comment by SreejanPersonal** [comment]
Fixed The Issue with `requests.exceptions.JSONDecodeError` 🤗
Updated Groq's File
