### ISSUE TITLE
key error data

### ISSUE THREAD

**Issue by TheBlurHacker** [SreejanPersonal/JARVIS-AGI#3]
Traceback (most recent call last):
  File "c:\Users\dell\.vscode\Projects\Jarvis\gpt-4o.py", line 103, in <module>
    results, images = farfalle.process_sources(sources)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\.vscode\Projects\Jarvis\gpt-4o.py", line 73, in process_sources
    for result in sources['data']['results']:
                  ~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by SreejanPersonal** [comment]
Farfalle Gpt 4o usage is exceeded. It is the only website offering free gpt 4o. Soon it will return. Currently too many people have used it. Try using a different model or provider. And please don't post issues like this. This is a rate limit issue. Atleast check the response first what you are getting. Just Pasting the error without even debugging it. 

Be a coder. Be a programmer. Hope so you will understand
